// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHgmKiLLQve55NixwoeSTOMeSe-5xEkG0',
    appId: '1:197398335162:web:14a15377ccd590933ebc83',
    messagingSenderId: '197398335162',
    projectId: 'evocity-app',
    authDomain: 'evocity-app.firebaseapp.com',
    storageBucket: 'evocity-app.appspot.com',
    measurementId: 'G-FN8QTQTD0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCed6DfNuipPWSbuG4gkwHLrkIwu5oxsq4',
    appId: '1:197398335162:android:8fa196794bc0b1bf3ebc83',
    messagingSenderId: '197398335162',
    projectId: 'evocity-app',
    storageBucket: 'evocity-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2dSIwhuQQDuIwQZ5p00tisV-M9BlGjoA',
    appId: '1:197398335162:ios:09619d1c92e7e07c3ebc83',
    messagingSenderId: '197398335162',
    projectId: 'evocity-app',
    storageBucket: 'evocity-app.appspot.com',
    iosClientId: '197398335162-56bk6lv55jq2vetp759t4fsf7uveuikp.apps.googleusercontent.com',
    iosBundleId: 'com.example.testlogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2dSIwhuQQDuIwQZ5p00tisV-M9BlGjoA',
    appId: '1:197398335162:ios:09619d1c92e7e07c3ebc83',
    messagingSenderId: '197398335162',
    projectId: 'evocity-app',
    storageBucket: 'evocity-app.appspot.com',
    iosClientId: '197398335162-56bk6lv55jq2vetp759t4fsf7uveuikp.apps.googleusercontent.com',
    iosBundleId: 'com.example.testlogin',
  );
}
